# Generated by Django 3.2.3 on 2021-05-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('clap_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('histories', models.JSONField(blank=True, null=True)),
                ('moderator_note', models.TextField(blank=True, null=True)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='clap_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='histories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(blank=True)),
                ('comment', models.TextField()),
                ('clap_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('histories', models.JSONField(blank=True, null=True)),
                ('moderator_note', models.TextField(blank=True, null=True)),
                ('on_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.comment')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='on_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article'),
        ),
    ]
