# Generated by Django 3.2.3 on 2021-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbs/noimage.png', upload_to='thumbs/'),
        ),
    ]
