# Generated by Django 3.2.3 on 2021-05-19 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_article_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='claps',
            field=models.ManyToManyField(related_name='users_claps', to=settings.AUTH_USER_MODEL),
        ),
    ]
